# Generated by Django 3.1.1 on 2021-02-16 12:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_timestamp'),
    ]

    operations = [

    ]
